name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libssl-dev libffi-dev \
              python3-dev python3-pip git zip unzip openjdk-17-jdk \
              libsqlite3-dev libpng-dev libjpeg-dev zlib1g-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload Artifact (APK)
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: bin/*.apk

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: bin/*.apk
